### ISSUE TITLE
maven-build-scanner ignores -T arguments

### ISSUE THREAD

**Issue by ArkadyKarev** [intuit/maven-build-scanner#90]
Hi, I'm trying to use maven-build-scanner with openjdk 15, and looks like that ignores mvn arguments.
For instance, when I use -T 8 or -T 1C, it shows only `Thread #1`

![image](https://user-images.githubusercontent.com/2506172/139603428-aa7722ff-79a9-49d1-bae5-28cc778c4e26.png)

Am I doing something wrong? Please help me to figure out, because it seems to be a great tool.

And also when I'm running the build with `mvn -T 1C` argument, 
in the cmd I can see 
`[INFO] Using the MultiThreadedBuilder implementation with a thread count of 8`

but dashbord says
`mvn -s /Users/arkady/.m2/settings.xml -T 8 -Pdefault clean test`
like I run it with `-T 8`

```
java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

mvn -v
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/Cellar/maven/3.8.3/libexec
Java version: 15.0.2, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
Default locale: en_RU, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by alexec** [comment]
Not sure what’s happened here. It only reports threads encountered. It could be your build somehow only runs single threaded, eg due to some dependency

**Comment by ArkadyKarev** [comment]
@alexec thanks for your response. I tried to run it in several different project, and result is the same - it show only 1 thread. Could you give me advice how I can debug it, please? Or any other thoughts?

**Comment by amanjadon54** [comment]
I face the same issue as well with the usage.
@ArkadyKarev were you able to resolve it?

**Comment by ArkadyKarev** [comment]
> I face the same issue as well with the usage. @ArkadyKarev were you able to resolve it?

Hi, nah, this project looks abandoned. I've decided not to use it

**Comment by alexec** [comment]
The graph is correct. Your build is running single-threaded, -T is not having an impact on it. It is reporting -T8 because that is what Maven is reporting, you're running one thread per core, and you have 8 cores.

You should expect a single-thread if, for example, you only have one Maven module in your project. This is what your example shows. If it still run single-threaded when you have multiple modules, then your modules are dependant on one another. That maybe just how you project works.

The goal of the project is speed up builds by providing insights. The insight I glean from your build is you assemble stage is long.

This is an OSS project, so help and support can only be given on best effort basis.

This project is not abandoned, but it is considered feature complete. It will continues to get security updates for example.
